from sys import argv
import string 

script, filename, outputName = argv

def compareStrings(s1, s2):
    return s1.translate(None, string.whitespace) == s2.translate(None, string.whitespace)

def getName(line):
    reversedName = ''
    isArray = False
    for c in reversed(line.rstrip()):
        if c == ';':
            pass
        elif c == ']':
            isArray = True
        elif c == '[':
            isArray = False
        elif c == ' ':
            break;
        elif not(isArray):
            reversedName += c
    return reversed(reversedName)


def parseUniformInfo(line):
    info = []
    typed = ''
    name = ''
    value = ''
    if line.find('mat4') >= 0:
        typed = 'm4'
        value = 'new THREE.Matrix4()' 
    elif line.find('vec4') >= 0:
        typed = 'v4'
        value = 'new THREE.Vector4()' 
    elif line.find('vec3') >= 0:
        typed = 'v3'
        value = 'new THREE.Vector3()'
    elif line.find('vec2') >= 0:
        typed = 'v2'
        value = 'new THREE.Vector2()'
    elif line.find('float') >= 0:
        typed = 'f'
        value = '0.0'
    elif line.find('int') >= 0:
        typed = 'i'
        value = '0'
    else line.find('sampler2D') >= 0:
        typed = ''
        value = 'null'

    if line.find('[') >= 0:
        typed += 'v'
        value = '[]'
    
    name = getName(line)

    info.append(typed)
    info.append(name)
    info.append(value)
    return info

isVertex = False
isFragment = False
uniforms = []
vertex = []
fragment = []

#Parse through file
with open(filename) as file:
    for line in file:
        if compareStrings(line, 'BEGIN VERTEX'):
            isVertex = True
        elif compareStrings(line, 'END VERTEX'): 
            isVertex = False
        elif compareStrings(line, 'BEGIN FRAGMENT'): 
            isFragment = True
        elif compareStrings(line, 'END FRAGMENT'):
            isFragment = False
        if isVertex:
            if line.find('uniform') >= 0: #check if line is uniform declaration
                uniforms.append(parseUniformInfo(line))
            vertex.append(line)
        if isFragment:
            if line.find('uniform') >= 0: #check if line is uniform declaration
                uniforms.append(parseUniformInfo(line))
            fragment.append(line)

def writeUniforms(file)

def writeShader(file, shader)

#Begin writing to new JS file
output = open(outputName+'.js', 'w')

output.write('/**')
output.write('* This file was generated by the shaderToPPScript tool')
output.write('*/')
output.write('')
output.write('THREE.'+outputName+' = {')
output.write('')
output.write('uniforms: {')
writeUniforms(output)
output.write('},')
output.write('')
output.write('vertexShader: [')
output.write('')
writeShader(output, vertex)
output.write('')
output.write('].join( "\n" ),')
output.write('')
output.write('fragmentShader: [')
output.write('')
writeShader(output, fragment)
output.write('')
output.write('].join( "\n" )')
output.write('')
output.write('};')

output.close()